server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost/kingmaker
    username: root
    password: dmArtini1994
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  security:
    oauth2:
      client:
        accessTokenUri: http://localhost:8080/oauth/token
        userAuthorizationUri: http://localhost:8080/oauth/authorize
        clientId: acme
        clientSecret: acmesecret
      resource:
        userInfoUri: http://localhost:8080/user